default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_app_development
  user: postgres
  password:

test:
  <<: *default
  database: recipe_app_test
  user: postgres
  password:

production:
  <<: *default
  database: recipe_app_production
  username: recipe_app
  password: <%= ENV['MOVIE_PROJECT_DATABASE_PASSWORD'] %>
